### ISSUE TITLE
 Caused by: java.lang.IllegalArgumentException: Unknown URL

### ISSUE THREAD

**Issue by hisham2007** [Mauker1/MaterialSearchView#10]
Caused by: java.lang.IllegalArgumentException: Unknown URL content://br.com.mauker.materialsearchview.defaultsearchhistorydatabase/history

it seems that you removed provider from library but didn't document in read me that you should put it in app

**Comment by hisham2007** [comment]
mmm
even after putting provider to my app I still face issue
Caused by: java.lang.IllegalArgumentException: Unknown URL content://br.com.mauker.materialsearchview.defaultsearchhistorydatabase/history

**Comment by Mauker1** [comment]
I've added the following note:

> Note: To get the library to work, now you have to implement a class named MsvAuthority inside the br.com.mauker package on your app module, and it should have a public static String variable called CONTENT_AUTHORITY. Give it the value you want and don't forget to add the same name on your manifest file.

**Comment by hisham2007** [comment]
now it is working. thank you :)

**Comment by Mauker1** [comment]
You're very welcome! 👍

**Comment by andy82302** [comment]
i use this but no work

**Comment by andy82302** [comment]
![default](https://user-images.githubusercontent.com/26705693/35083351-b1470680-fc59-11e7-94f2-650052888168.PNG)
![2](https://user-images.githubusercontent.com/26705693/35083352-b577df5e-fc59-11e7-832f-d8a37bf0dc39.PNG)
