### ISSUE TITLE
Is there a way to capture touch event on the textfield of the search view?

### ISSUE THREAD

**Issue by gregEstoke** [Mauker1/MaterialSearchView#101]
I need to perform an action, if a search has been done, then the user clicks on the textView to refine his search, I need to delete the previous results. Is there a way to achieve that? I tried to put a touch listener on the rootview but this doesn't do the trick (event not captured)...

**Comment by Mauker1** [comment]
You want to delete the suggestion from the list if the user clicks on it?

**Comment by gregEstoke** [comment]
No, I'd like to get a callback when focus is set in the textInput of the search bar

**Comment by gregEstoke** [comment]
ok my bad; I could get it with:
`EditText editText = (EditText) searchView.findViewById(R.id.et_search);
        editText.setOnTouchListener(this); `

**Comment by Mauker1** [comment]
Oh, okay then, I'll close the issue 👍
