### ISSUE TITLE
MaterialSearchView is below the toolbar

### ISSUE THREAD

**Issue by GabrielKuka** [Mauker1/MaterialSearchView#106]
This is my layout. The materialsearchview is in the end as in the sample. But when I run the searchview stands behind the toolbar. What could be the issue?

`<?xml version="1.0" encoding="utf-8"?>
  <android.support.constraint.ConstraintLayout 
   xmlns:android="http://schemas.android.com/apk/res/android"
   xmlns:app="http://schemas.android.com/apk/res-auto"
   xmlns:tools="http://schemas.android.com/tools"
   android:layout_width="match_parent"
   android:layout_height="match_parent"
   tools:context="com.katana.memo.memo.Activities.Homepage">

    <android.support.v7.widget.Toolbar
        android:id="@+id/appToolbar"
        android:layout_width="0dp"
        android:layout_height="56dp"
        android:background="@color/colorAccent"
        android:elevation="4dp"
        android:theme="@style/ToolbarTheme"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerView"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginTop="15dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/appToolbar"
        app:layout_constraintVertical_bias="0.0" />

    <br.com.mauker.materialsearchview.MaterialSearchView
        android:id="@+id/search_view"
        style="@style/MaterialSearchViewStyle"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    </android.support.constraint.ConstraintLayout>`

**Comment by Mauker1** [comment]
How did you solve the issue?

**Comment by GabrielKuka** [comment]
The issue was with elevation. The elevation of toolbar was 4dp while at the searchview I hadn't specified one. The elevation of searchview must be higher than the elevation of toolbar.

**Comment by shihabmi7** [comment]
But elevation supports from API level 21 . So ? 

After following your guide no change.

**Comment by Mauker1** [comment]
You still have to place the XML tag below everything else on the layout.

**Comment by shihabmi7** [comment]
Solved.. following your tips
