### ISSUE TITLE
How to disable voice button in Kotlin

### ISSUE THREAD

**Issue by GabrielKuka** [Mauker1/MaterialSearchView#107]
I have set up my searchview, but I would like to take away the voice button. How can I do that? I couldn't find a method for that. I also tried setVoiceIcon(null) but Kotlin gives me an error of a non-null type-thing.

**Comment by Mauker1** [comment]
You can user `searchView.setVoiceIcon(null);`.

**Comment by Mauker1** [comment]
I'll have to dig a bit into this.

**Comment by GabrielKuka** [comment]
Okay. Thank you again!

**Comment by Mauker1** [comment]
Can you show me the error you're getting?

**Comment by GabrielKuka** [comment]
![img](https://user-images.githubusercontent.com/17888328/28425667-4be57992-6d71-11e7-9486-dc74e44ad672.png)

**Comment by Mauker1** [comment]
Try to use this: `setVoiceIcon(0)`

**Comment by GabrielKuka** [comment]
Now it works. The icon disappeared. Thank you sir!!!

**Comment by Mauker1** [comment]
You're welcome!
