### ISSUE TITLE
Problem with searchview in API 24

### ISSUE THREAD

**Issue by afazolo** [Mauker1/MaterialSearchView#109]
Any clue why my searchview does not open with API 24, although it does activate the keyboard or works well with API 19? 
EDIT:
It seems the same problem here https://github.com/Mauker1/MaterialSearchView/issues/87 . Most likely conflit with AppBarLayout on API 24/25

**Comment by afazolo** [comment]
Never mind. As peterbetos said in his last post here https://github.com/Mauker1/MaterialSearchView/issues/38 ,  the trick is to adjust the elevation above 5 since the appbarlayout has elevation 4.

**Comment by Mauker1** [comment]
Like he said of #38 the elevation should be higher. That's valid for any kind of view.

**Comment by afazolo** [comment]
Yeap. My mistake!
