### ISSUE TITLE
Abandon Content Provider

### ISSUE THREAD

**Issue by Mauker1** [Mauker1/MaterialSearchView#11]
To allow the use of the `Content Provider` as the database access, I had to do some hackish code which I'm not very proud of. So, one option to keep the support for search history and search suggestions is to change the `CursorAdapter` for something else, and abandon the Content Provider once and for all.

**Comment by peterbetos** [comment]
Would you want someone to do it via Realm? 😃

**Comment by Mauker1** [comment]
It would be very interesting indeed :)

Content Provider may work just fine, but I don't like how hacky it looks to work with a custom provider.

**Comment by jssingh** [comment]
Just use any small ORM along with Rx to write to the database in the IO thread. I can try to take a stab at it if someone else isn't working on it.

**Comment by peterbetos** [comment]
Yep. Currently not working on it. What ORM will you use?

**Comment by jssingh** [comment]
Sorry didn't see you reply earlier. We can really start off with either of the following lightweight ORM's:
- OrmLite
- GreenDAO
- Cupboard
- Realm

You have a preference?

**Comment by peterbetos** [comment]
My preference is Realm, but I fear we might not support JACK Compiler if we use that. Can you try with others if JACK works, especially the one that only uses annotation, like GreenDAO's latest version?

**Comment by jssingh** [comment]
I'd recommend that we start using the JACK toolchain on this project now, if that is our concern. That way, we only look for implementing libraries/features that are compatible. 

I'll play around with GreenDAO soon.

**Comment by peterbetos** [comment]
Will test JACK then ;)

**Comment by peterbetos** [comment]
@jssingh Your jack wish is granted: 😉 
https://github.com/Mauker1/MaterialSearchView/pull/68

**Comment by jssingh** [comment]
👍

Will start work on greenDAO shortly.

**Comment by AdamMc331** [comment]
Are we sure an ORM is a great idea? I think it's super useful, but my fear is that it adds to the memory footprint of the library more than something built in, or even letting the users handle it. 

What tends to be more important to you? The size of the library or ease of use?

**Comment by AdamMc331** [comment]
In my attempts to switch to RecyclerView for #99, I may drop the content provider as RecyclerView does not have a CursorAdapter, but it would still be using SQLite.

**Comment by Mauker1** [comment]
That's exactly what I thought @AdamMc331 . #99 might just solve this issue as well. And it'll make us one step close to V 2.0 :)

**Comment by Mauker1** [comment]
Took me a while (A long while I know, sorry), but I finally did it.
