### ISSUE TITLE
Throws Nullpointerexpection in fragment menuitem

### ISSUE THREAD

**Issue by Faiyyaz** [Mauker1/MaterialSearchView#110]
This is the stacktrace of the above error

` java.lang.NullPointerException: Attempt to invoke virtual method 'void br.com.mauker.materialsearchview.MaterialSearchView.setOnQueryTextListener(br.com.mauker.materialsearchview.MaterialSearchView$OnQueryTextListener)' on a null object reference`

**Comment by Mauker1** [comment]
Can you show more of your setup, please? Which line caused it?

**Comment by Mauker1** [comment]
We need more details to look into this problem. I'm closing this issue since it's been a while and there was no answer. If you're still having this problem, please share the code and I'll reopen the issue.
