### ISSUE TITLE
searchView.removeSuggestion() not working.

### ISSUE THREAD

**Issue by mak12** [Mauker1/MaterialSearchView#113]
I am trying to remove one individual suggestion by passing that suggestion but its not working, is there any way of removing any particular suggestion

**Comment by Mauker1** [comment]
Could you provide the code where you're trying to remove the suggestion?

**Comment by mak12** [comment]
yes the problem was because of case sensitivity , and is there any way of removing specofic history?

**Comment by Mauker1** [comment]
There isn't one, yet. But I've opened an issue (#114) to remind me of adding this feature later. Thanks for the idea.
