### ISSUE TITLE
Convert To Kotlin

### ISSUE THREAD

**Issue by AdamMc331** [Mauker1/MaterialSearchView#119]
Now that Kotlin is officially supported, and that Mauker and I have begun using it even more, I think it would be worthy to consider transitioning this library to Kotlin. More and more developers and libraries are using it, and so I think it would help for us to be compatible with that.

**Comment by Mauker1** [comment]
I had that on my mind for quite a while now. Good thing you created this issue. Let's start this conversion, and while we're at it we could migrate the ContentProvider logic to Room or something else and make this lib easier to use. 

I'll make this a milestone to version 2.0.

**Comment by AdamMc331** [comment]
@Mauker1 Would you prioritize the move to Kotlin before Room, or do that one first? I'd hate to do them in one PR.

**Comment by Mauker1** [comment]
Done in https://github.com/Mauker1/MaterialSearchView/commit/c9e86b6354b13faf60938227818925ad41a5bfce
