### ISSUE TITLE
ProGuard hint

### ISSUE THREAD

**Issue by hisham2007** [Mauker1/MaterialSearchView#12]
Please add this note to read me:

add these lines to pro guard:

-keep class br.com.mauker.MsvAuthority
-keepclassmembers class br.com.mauker.** { *; }

**Comment by Mauker1** [comment]
Care to explain why? When you imported the version 1.1.0 did those files get deleted?

**Comment by frostymarvelous** [comment]
Thanks. Came here for this.

This is the error I was getting `Failed to find provider info for br.com.mauker.materialsearchview.defaultsearchhistorydatabase` and it was crashing when I searched.

This fixed the crashes.

**Comment by Mauker1** [comment]
Can you provide the full stack trace for that error? What message shows up when it crashes?

**Comment by frostymarvelous** [comment]
It wouldn't help. 

It was after proguard obfuscation. Applying the rules above fixed it.

**Comment by frostymarvelous** [comment]
To be clear, the library works fine. In fact, I need to thank you so much for such awesome work. 

Last I wanted to implement search, I skipped the provider portion. 
With just a few lines, you've got me going strong. 

The problem only appears since I think proguard removes some classes.

**Comment by Mauker1** [comment]
You're very welcome, and thanks too!

So, did you make your own version without the Search History stuff? Or did you implement a different logic for this part? If you did, I would be very happy to see how it was done :)

And it seems that proguard is removing those provider classes in some cases, I think I'll add those lines on the README.

**Comment by frostymarvelous** [comment]
What I made initially was the simple actionbar action. No search history of
any kind! Lol.
It sucked.

Do add them. I'm lucky they were already available. Tracking proguard
issues can be a PITA.

**Comment by hisham2007** [comment]
Sorry to be late .
I mastered proguard as I face tons of issues with it :)
So I expected this error when you told me in another defect that I must add a class in my project with specific name and specific path. name should be the same in manifest.

I said to my self, he must be calling this class and its static members in runtime from library code. and here I remember that there is someone will not be happy with that. it is Proguard.

So no need for stacktrace. it is expected :)

**Comment by Mauker1** [comment]
I'll add it now to the README then, thank you so much for the help guys.

**Comment by hisham2007** [comment]
By the way, I played with library as our client needs predefined keywords be displayed once you click search button. 
I found you display history only. So, I did a workaround by adding all predefined keywords to history once I open activity :)
I added a public method with the same signature as addSuggestions and I put type 1 instead of 0  :)

**Comment by Mauker1** [comment]
Oh yes. The suggestion list only works with the filter. I might add a fixed suggestion list as well in the future, it might be a good idea :)
