### ISSUE TITLE
First time animation

### ISSUE THREAD

**Issue by sfilmak** [Mauker1/MaterialSearchView#122]
Hello! 

I'm sorry, but how can I fix a problem when animation doesn't appear after the first launch of the application? This issue is described here too: https://github.com/Mauker1/MaterialSearchView/issues/79

Thank you!

**Comment by Mauker1** [comment]
Hello!

No reason to be sorry, I'm always glad when the community helps me to track those bugs down and make the lib more mature.

So, MSV is going through a major refactor right now as we are changing it to Kotlin and dropping the `ContentProvider` and many other things. We will also try to track this bug down on the process.

Thanks!

**Comment by sfilmak** [comment]
Thank you!
