### ISSUE TITLE
i cant find MsvAuthority class in the package

### ISSUE THREAD

**Issue by iloukou** [Mauker1/MaterialSearchView#123]

**Comment by Mauker1** [comment]
Have you created the class?

**Comment by iloukou** [comment]
Thank you for answered.I did it but i dont know what to change in the
manifest

2018-02-25 14:46 GMT+00:00 Maurício C. P. Pessoa <notifications@github.com>:

**Comment by Mauker1** [comment]
You have to create the `MsvAuthority` class and assing your own, and unique, content authority. Later on, add the `<provider>` tag on your android manifest with the same content authority you defined on the class.

**Comment by Mauker1** [comment]
I'm closing this issue since there was no further input from the user. Feel free to comment and I'll open it again.
