### ISSUE TITLE
KeyBoard not showing in Kitkat

### ISSUE THREAD

**Issue by RahilRK** [Mauker1/MaterialSearchView#125]
KeyBoard not showing in Kitkat

**Comment by Mauker1** [comment]
Could you elaborate further, please? When is the keyboard not showing up?

**Comment by RahilRK** [comment]
solved.....

**Comment by Mauker1** [comment]
What was the problem?

**Comment by RahilRK** [comment]
In **setting** under **Keyboard and Input methods**..
under Default, turn **off** physical keyboard.

**Comment by Mauker1** [comment]
Ok, thanks for the reply.
