### ISSUE TITLE
How to change suggestion background color from gray to our choice ?

### ISSUE THREAD

**Issue by RahilRK** [Mauker1/MaterialSearchView#126]
How to change suggestion background color from gray to our choice ?

**Comment by Mauker1** [comment]
There's a method called `setBackgroundColor(int color)` that will take a color of your choice.

**Comment by RahilRK** [comment]
ok brother i will see to it....

**Comment by Mauker1** [comment]
let me know if it has the desired effect :)

**Comment by RahilRK** [comment]
![screenshot_1520654828](https://user-images.githubusercontent.com/36914614/37238176-b85640ca-2446-11e8-8900-3bea420004dc.png)

**Comment by RahilRK** [comment]
![screenshot_1520655678](https://user-images.githubusercontent.com/36914614/37238266-9a89f56c-2448-11e8-8f5c-8f8fbddcbbc3.png)


i had just solved it by adding new color.xml, and then calling it in styles of MaterialSearchViewStyle.

**Comment by RahilRK** [comment]
so now how to change **suggestions text color** brother from white to **as per our choice** ??
