### ISSUE TITLE
so now how to change suggestions text color brother from white to as per our choice ??

### ISSUE THREAD

**Issue by RahilRK** [Mauker1/MaterialSearchView#129]

**Comment by Mauker1** [comment]
This will be added in the next release. As of version 1.2.2 it's not possible yet.

**Comment by RahilRK** [comment]
**next release** till **when**...bro??

**Comment by Mauker1** [comment]
Since there are two quick fixed, I believe I could launch a version before 2.0 with those fixed. I'll be looking into that later this week.

**Comment by RahilRK** [comment]
OK,  when you launch... please let me know....

**Comment by Mauker1** [comment]
Since this issue is the same as #13 I'll close it.
