### ISSUE TITLE
Make possible to style suggestion list

### ISSUE THREAD

**Issue by Mauker1** [Mauker1/MaterialSearchView#13]
As the lib is right now, it doesn't allow the developer to change the icons or the text color of the list. It's a good idea to make those editable.

**Comment by FunnyDevs** [comment]
any news???

**Comment by mtiidla** [comment]
Is it possible to change the background of suggestions list?

Currently the code is not setting the drawable as background in JELLY_BEAN

`public void setSuggestionBackground(Drawable drawable) {
        // Method change in jelly bean
        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
            mSuggestionsListView.setBackground(getBackground());
        } else {
            //noinspection deprecation
            mSuggestionsListView.setBackgroundDrawable(drawable);
        }
    }`

**Comment by Mauker1** [comment]
As this is a bit of a "big" change, I'll move this to 1.3.0.

**Comment by dperez848** [comment]
Do you have a clue of when this is going to be able to do?

**Comment by Mauker1** [comment]
I'll wait for the code review. Once that's done I'll release another version with this feature and close this issue.
