### ISSUE TITLE
Getquery

### ISSUE THREAD

**Issue by spybat2010** [Mauker1/MaterialSearchView#131]
so im beginner , i want to get text from search view and add it to another string 
how can i do it ?

**Comment by Mauker1** [comment]
You want the get the query string and append something to it, and then place it back on the search view?

**Comment by Mauker1** [comment]
To get the current text on the Search View, use `getCurrentQuery()`. 
If you want to set a String to the Search View, you can call `setQuery(String query, boolean shouldSubmit)`.
