### ISSUE TITLE
how get search back icon click event?

### ISSUE THREAD

**Issue by kukadiyaAni** [Mauker1/MaterialSearchView#14]
Hello,

I am using your library MatrialSearView and it have awesome animation.

when I am click on back button and close button nothing happen.

Close button display right side of Search View after search text.

Can you please how can I get close and back button click event in SerachView.

Regards

**Comment by Mauker1** [comment]
Hello,

You can't get this event directly, but it's possible to know when the view is being closed.

To do that, you have to set a `SearchViewListener`, like the following:

```java
searchView.setSearchViewListener(new MaterialSearchView.SearchViewListener() {
            @Override
            public void onSearchViewOpened() {
                // Do something once the view is open.
            }

            @Override
            public void onSearchViewClosed() {
                // Do something once the view is closed.
            }
        });
```

You can also make the system back button close the search view doing the following inside your `Activity`:

```java
@Override
public void onBackPressed() {
    if (searchView.isOpen()) {
        // Close the search on the back button press.
        searchView.closeSearch();
    } else {
        super.onBackPressed();
    }
}
```

**Comment by AdamMc331** [comment]
The back button snippet is also mentioned in the README. :)
