### ISSUE TITLE
SearchView Animator Issue

### ISSUE THREAD

**Issue by leoemili** [Mauker1/MaterialSearchView#140]
I noticed that the first time I open the Searchview the animator doesn't work properly. I mean I cannot see any animation/transition. Then if I close the Searchview it and reopen it, it works perfectly.
Tested on API 24, Android 7.0

**Comment by Mauker1** [comment]
This is the same problem as #79 . So I'm closing this issue here.

It's a bug that happens sometimes, but I'm still not sure why it is happening. I'm looking forward to solve this issue in a future release.
