### ISSUE TITLE
How to change the default text in Searchview?

### ISSUE THREAD

**Issue by leoemili** [Mauker1/MaterialSearchView#141]
I'd like to change the default text shown in the SearchView, how can I do it?

**Comment by Mauker1** [comment]
You mean the text hint?

If that's the case, you can style the view through XML as stated [on the README](https://github.com/Mauker1/MaterialSearchView#styling-the-view).

You can also modify the hint programmatically by calling: [`searchView.setHint()`](https://github.com/Mauker1/MaterialSearchView/blob/master/library/src/main/java/br/com/mauker/materialsearchview/MaterialSearchView.java#L874)

**Comment by leoemili** [comment]
Thanks a lot

**Comment by Mauker1** [comment]
You're welcome!
