### ISSUE TITLE
Remove voice icon

### ISSUE THREAD

**Issue by maxi182Eman** [Mauker1/MaterialSearchView#150]
I can't find a public method in the api to let us remove the voice icon, how could be this possible to do?
Thanks

**Comment by Mauker1** [comment]
You can try: `setVoiceIcon(0)`

**Comment by AdamMc331** [comment]
I will take this one on. :) We can add a custom view attribute to have something like `app:voiceIconEnabled="false"` in XML. 

In the mean time, you can use Mauker's code programatically as a work around.
