### ISSUE TITLE
Unknown URL content://br.com.sagar.materialsearchview.defaultsearchhistorydatabase/history

### ISSUE THREAD

**Issue by sagarnayak** [Mauker1/MaterialSearchView#155]
Anyone got any hint about this.
I have created the authority -
`
public class MsvAuthority {
    public static final String CONTENT_AUTHORITY = "br.com.sagar.materialsearchview.searchhistorydatabase";
}
`

and then used in the manifest - 

`
 <provider
            android:name="br.com.mauker.materialsearchview.db.HistoryProvider"
            android:authorities="br.com.sagar.materialsearchview.searchhistorydatabase"
            android:exported="false"
            android:protectionLevel="signature"
            android:syncable="true" />
`

but I am getting the error -
**Unknown URL content://br.com.sagar.materialsearchview.defaultsearchhistorydatabase/history**

my questions is-
can I put the MsvAuthority.java at any place in my project structure?
what are the relation between the name and authorities in the manifest with the MsvAuthority.java and my package name?

I am not getting this. anyone with any clue please do help.

**Comment by sandeepkumarmishra354** [comment]
create package into app>java>br.com.mauker and put the file it works...

**Comment by Mauker1** [comment]
As sandeep said, you need to create the file under the `br.com.mauker` package for it to work.
