### ISSUE TITLE
WARNING: API 'variant.getMergeResources()'

### ISSUE THREAD

**Issue by sahuadarsh0** [Mauker1/MaterialSearchView#156]
WARNING: API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app

**Comment by Mauker1** [comment]
Should probably have been fixed in the latest version. Feel free to reopen if it stills pops up.
