### ISSUE TITLE
The XML is not visible 

### ISSUE THREAD

**Issue by alonsd** [Mauker1/MaterialSearchView#160]
I want to try using this library but when putting it into my XML the view is not visible at all. 

I can't seem to get it working. As you can see, I see a view with some width but 0 height on my xml.  Why is this happening? 

![image](https://user-images.githubusercontent.com/29747936/69231990-cc5d0380-0b92-11ea-9cdb-e4cc6570012e.png)

**Comment by Mauker1** [comment]
MSV should have `match_parent` on both width and height attributes. Also, don't forget to make it the last element in your XML tree. And if your root element has padding, it'll also affect the MSV.

**Comment by alonsd** [comment]
> MSV should have `match_parent` on both width and height attributes. Also, don't forget to make it the last element in your XML tree. And if your root element has padding, it'll also affect the MSV.

Please look at the date I posted this question, I don't ever remember what this repository is about. 
You could just close the question without even answering, neither makes any difference at this point in time.
