### ISSUE TITLE
Solution: Failed to get authority

### ISSUE THREAD

**Issue by xeinebiu** [Mauker1/MaterialSearchView#162]
Setting the exported attribute to true in the provider tag in the manifest worked for me
android:exported="true"

**Comment by Mauker1** [comment]
The content provider will be removed in V 2.0. I've pushed the commit here: https://github.com/Mauker1/MaterialSearchView/commit/ca7cfa411c90822c7e5ce3fd82b22b352c3aef89

I'll soon release an alpha version. Setup will be much easier now.
