### ISSUE TITLE
Implementing searchview

### ISSUE THREAD

**Issue by ambitamber** [Mauker1/MaterialSearchView#168]
Hello,

I have implemented the searchview. I have error message. 

`E/ActivityThread: Failed to find provider info for br.com.mauker.materialsearchview.defaultsearchhistorydatabase`
I know the error is from provider in Manifest. 

I have added MsvAuthority in app level. 
under my package name. 

This is what I have added to manifest file.

`<provider
            android:name="br.com.mauker.materialsearchview.db.HistoryProvider"
            android:authorities="com.tamberlab.newz.MsvAuthority"
            android:exported="false"
            android:protectionLevel="signature"
            android:syncable="true"/>`

Is there something I am doing wrong?

**Comment by Mauker1** [comment]
You have to add the MsvAuthority under the `br.com.mauker` package name.

**Comment by ambitamber** [comment]
I am using 1.3.0-rc01@arr.

I don't have option to add java file to the package.

![Annotation 2020-09-05 180536](https://user-images.githubusercontent.com/50850921/92314181-84349380-efa2-11ea-9db4-18d59b20ebd0.jpg)

**Comment by ambitamber** [comment]
I figure it out.
