### ISSUE TITLE
Installation did not succeed. The application could not be installed: INSTALL_FAILED_CONFLICTING_PROVIDER

### ISSUE THREAD

**Issue by sahuadarsh0** [Mauker1/MaterialSearchView#170]
## Installation did not succeed.The application could not be installed: INSTALL_FAILED_CONFLICTING_PROVIDER

`
   ####  implementation 'br.com.mauker.materialsearchview:materialsearchview:1.3.0-rc01'
`

   ```
 <provider
        android:name="br.com.mauker.materialsearchview.db.HistoryProvider"
        android:authorities="br.com.mauker.materialsearchview.searchhistorydatabase2"
        android:exported="false"
        android:protectionLevel="signature"
        android:syncable="true"/>

```
```

package br.com.mauker;

public class MsvAuthority {
    public static final String CONTENT_AUTHORITY = "br.com.mauker.materialsearchview.searchhistorydatabase2";
}
```

If  I Change the content provider then a new error is showing error inflating xml view

**Comment by Mauker1** [comment]
You need to define your own provider. Or you could try the v2.0 alpha version that skips this setup altogether.

As for the second error, could you show the full stack trace, please?

**Comment by sahuadarsh0** [comment]
solved
