### ISSUE TITLE
notifyDataSetChanged() for Adapter

### ISSUE THREAD

**Issue by zorroblue** [Mauker1/MaterialSearchView#19]
In case I wanted to remove suggestions which I have already clicked, I would have to do a notifyDataSetChanged() for the adapter .I couldn't see a workaround with my brief scanning of the source code.. Any insights on this?

**Comment by Mauker1** [comment]
I'll take a look at this.

**Comment by Mauker1** [comment]
@AdamMc331 Any ideas?

**Comment by AdamMc331** [comment]
@zorroblue and @Mauker1 I've submit a PR for this. All I've added is an accessor method for the adapter that would give the user's more explicit control over it. Let me know if this is good enough for now.
