### ISSUE TITLE
OnSearchViewOpened not called when shouldAnimate = true

### ISSUE THREAD

**Issue by Shargotth** [Mauker1/MaterialSearchView#20]
Hi,

I found a bug. When I set `shouldAnimate` to true, the callback `onSearchViewOpened` is never called.
I checked at the source and found this, I think it could be the cause of this usse : 

```
if(mShouldAnimate) {
        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            mRoot.setVisibility(View.VISIBLE);
            AnimationUtils.circleRevealView(mSearchBar);
        }
        else {
            AnimationUtils.fadeInView(mRoot);
        }

    } else {
        mRoot.setVisibility(View.VISIBLE);
        if(mSearchViewListener != null) {
            mSearchViewListener.onSearchViewOpened();
        }
    }
```

We see that the `SearchViewListener` is called only when `mShouldAnimate` is false.

Is their a reason for this?

**Comment by Mauker1** [comment]
Hello,

It seems I rushed a little bit when I coded that part and didn't notice that issue, I'll work on a fix, thanks!
