### ISSUE TITLE
Does it support Arabic or Persian preferebly? 

### ISSUE THREAD

**Issue by yousofkakhki** [Mauker1/MaterialSearchView#22]
hi thanks for ur cool library
i just wanted to know before implementation 
does this lib supports arabic or persian?
i mean my users have persian keyboard.

**Comment by Mauker1** [comment]
The answer is: **not yet**.

As seem on [this issue](https://github.com/Mauker1/MaterialSearchView/issues/8), it'll be supported on the next release of the lib.
