### ISSUE TITLE
Voice hint prompt

### ISSUE THREAD

**Issue by x4080** [Mauker1/MaterialSearchView#23]
Hi, first of all, great job

Can we change the text in the voice search hint prompt ? for your code below ? 

```
private void onVoiceClicked() {
        Intent intent = new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);
        intent.putExtra(RecognizerIntent.EXTRA_PROMPT, mContext.getString(R.string.hint_prompt));
....

```

Thanks

**Comment by Mauker1** [comment]
It's not possible at this time, but I liked the idea! I'll add this as a feature on the next release. Thanks!

**Comment by x4080** [comment]
cool, quick question, can we add suggestions on the fly when user typing the query? or should be at start before user typing? case use would be 'like' search filtering of query might be very handy

**Comment by Mauker1** [comment]
You can do both. Either add before the input, or you could also change them using the `OnQueryTextListener ` interface, so when the user types something, you could add a new suggestions array.

On a second thought. I might add a new method, like `addSuggestion(String suggestion)`, because right now you can only add all of them, or remove all of them.

**Comment by x4080** [comment]
that's good idea, so if the user typing "app" and OnQueryTextListener i added Apple, it will automatically displayed or it will displayed after the next character which is "appl"

and it's OK to remove and add all suggestions in the OnQueryTextListener?

**Comment by Mauker1** [comment]
That's one way of doing it with the current API, yes. But it's not good for performance. That's why I said I will add a method to insert and remove individual suggestions.

**Comment by x4080** [comment]
OK Thanks

**Comment by peterbetos** [comment]
You can otherwise implement a custom voice search listener so that the devs can implement the Intent on their own, especially inside the fragment (since views are purely context-based):

https://github.com/peterbetos/materialseachview/commit/aa6952faf0845249951c64beb9fd142aeb958d86
