### ISSUE TITLE
in landscape, with onscreen keyboard

### ISSUE THREAD

**Issue by x4080** [Mauker1/MaterialSearchView#24]
If we try to enter the text when in landscape mode with onscreen keyboard android will add new layer on top so the history/suggestions is hidden below

Is this the expected behaviour ?

![device-2016-06-26-093517](https://cloud.githubusercontent.com/assets/10181090/16360243/56a0891c-3b81-11e6-8107-e896ef25e8ae.png)

Thanks

Could be adding android:imeOptions="flagNoExtractUi" in the editText of the search bar fix this problem ?

**Comment by Mauker1** [comment]
I believe this is Android's default behavior, yes. But I'll try your suggestion and see if it helps. Thanks!

**Comment by x4080** [comment]
thanks hopefully it will work

**Comment by x4080** [comment]
Hello again, I already tested and it works by replacing 
```
                android:imeOptions="actionSearch"
```

to

```
                android:imeOptions="flagNoExtractUi"
```

in search_view.xml

**Comment by Mauker1** [comment]
It worked.
