### ISSUE TITLE
Package couldnt be installed message if more than 1 app in 1 phone using MaterialSearchView library

### ISSUE THREAD

**Issue by x4080** [Mauker1/MaterialSearchView#26]
Is there workaround for this ?

Thanks

![failed](https://cloud.githubusercontent.com/assets/10181090/16365700/76c07156-3c32-11e6-9426-34bf7684bc0c.png)

**Comment by Mauker1** [comment]
Which version are you using?

**Comment by Mauker1** [comment]
If you're using version 1.0.3, take a [look at this issue](https://github.com/Mauker1/MaterialSearchView/issues/7).

**Comment by x4080** [comment]
Hi, its 2.1.2 : 

```
classpath 'com.android.tools.build:gradle:2.1.2'
```

for both my project and MaterialSearchView Master

**Comment by Mauker1** [comment]
No, I mean, the version of the Material Search View.

**Comment by x4080** [comment]
Hmm, i just download from this github, maybe I made mistake will check it again

**Comment by Mauker1** [comment]
Look on your `build.gradle` file for the MSV dependency, something like: 

```
compile 'br.com.mauker.materialsearchview:materialsearchview:1.1.1
```

And tell me which version are you using.

**Comment by x4080** [comment]
Yes its already correct br.com.mauker.materialsearchview:materialsearchview:1.1.1, I dont know about the MaterialSearchView Master I downloaded from github though, can it be the old version ? Since I download it from the front page ?

**Comment by x4080** [comment]
Tried to create new project that is also using compile 'br.com.mauker.materialsearchview:materialsearchview:1.1.1', and it will show the same error message

**Comment by Mauker1** [comment]
Have you created the class `MsvAuthority` as it's described on the README? You have to do this, and assign your own authority String there. You can't use the same String on different apps, or the providers will conflict.

**Comment by x4080** [comment]
Yes MsvAuthority is created, oh maybe authority string thing that I dont change, I'll take a look, thanks

**Comment by x4080** [comment]
Yes, must change in the manifest and the MsvAuthority for unique CONTENT_AUTHORITY 

Thanks
