### ISSUE TITLE
Cannot change searchSuggestionBackground

### ISSUE THREAD

**Issue by x4080** [Mauker1/MaterialSearchView#27]
After some digging, to fix :

```
        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
            mSuggestionsListView.setBackground(drawable);
        } else {

```

before it was getBackground()

in the MaterialSearchView.java

hope it will help

**Comment by Mauker1** [comment]
That's mostly because I've inserted a "tint" background on the view. Try to change it's alpha value to 0 using the method `setTintAlpha`.

**Comment by x4080** [comment]
Oh I see, the thing is I wanted to change the background to white for cleaner look like google search bar :). Ok then
