### ISSUE TITLE
SearchSuggestionBackground problem

### ISSUE THREAD

**Issue by HotBitmapGG** [Mauker1/MaterialSearchView#31]
Set the background color of the searchSuggestionBackground invalid, are search_layover_bg, this is what problem, have a look at the trouble ，thank you.

**Comment by Mauker1** [comment]
I'm sorry, can you explain it better?

**Comment by HotBitmapGG** [comment]
<item name="searchSuggestionBackground">@color/search_layover_bg</item> Sets the background color is invalid, can only display the default gray, set to white, also showed that gray.

**Comment by Mauker1** [comment]
Please check this issue: https://github.com/Mauker1/MaterialSearchView/issues/27

**Comment by HotBitmapGG** [comment]
Thank you very much！

**Comment by Mauker1** [comment]
You're welcome!
