### ISSUE TITLE
Simplify the way to change the background color/transparency

### ISSUE THREAD

**Issue by Mauker1** [Mauker1/MaterialSearchView#37]
As per version 1.1.2 and before, to change the background color it's required to change the tint background along with the `ListView` background.

An idea would be to simplify this operation to a simple method.

**Comment by volkdown** [comment]
Hello, I would like to know. You have already added this option? Thanks in advance for your reply :)

**Comment by Mauker1** [comment]
Not yet @volkdown , but it's on the plans for the next release.
