### ISSUE TITLE
Support for transparent status bar?

### ISSUE THREAD

**Issue by MiralDesai** [Mauker1/MaterialSearchView#38]
This is how the library looks when I open the search on the screen I need it:

http://imgur.com/a/DK5qN

I have a navigation drawer here which is why the status bar is transparent. The Toolbar handles it just fine, showing up below the status bar. However when I initiate the SearchView, it goes behind the status bar.

Is there a fix/solution for this? Maybe something I've just missed on my side possibly?

Thanks.

**Comment by MiralDesai** [comment]
I've just noticed that putting the MaterailSearchView inside my DrawerLayout it causes my navigation drawer to stop receiving click events, so there might be a bigger problem.

Don't really know how or if this library has support for navigation drawers.

**Comment by AdamMc331** [comment]
Going off the top of my head, I can't see this being affected by the Nav Drawer, but it's possible.

Why are you putting it inside the DrawerLayout, and not at the root of the Activity?

I will try to recreate it this evening if I can.

**Comment by MiralDesai** [comment]
Deleted my comment because it was just an order issue in my layout. I put it inside my DrawerLayout because that is where my toolbar is. I have a base class for my Navigation drawer, and when I extend it in my main activity, it adds the toolbar automatically.

If I put the MaterialSearchView in my activity XML, then the search view would open underneath my toolbar.

**Comment by AdamMc331** [comment]
When you say it would open underneath the toolbar, that depends on how things are ordered. Is the root of your activity a `CoordinatorLayout`? If yes, try putting the MSV last, meaning it will be layered *on top* of everything else.

**Comment by MiralDesai** [comment]
The root of my activity is a `RelativeLayout`

**Comment by MiralDesai** [comment]
Ok that worked. Same issue as my opening post, however it's not inside my `DrawerLayout` now which is nice.

Just the transparent status bar issue.

**Comment by MiralDesai** [comment]
It doesn't even work when the status bar is opaque. http://imgur.com/a/ZNvws

I suppose the bug here is that the `SearchView` is not attaching to the `Toolbar` properly?

**Comment by Mauker1** [comment]
Try something like this on your XML:

```XML
<android.support.v4.widget.DrawerLayout ... >

	<android.support.design.widget.CoordinatorLayout ... >

	    <android.support.design.widget.AppBarLayout ... >
	    	<!-- Your toolbar here -->
	    </android.support.design.widget.AppBarLayout>

	    <!-- Or anything else you're using here -->
	    <FrameLayout
            android:id="@+id/container"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"/>

    </android.support.design.widget.CoordinatorLayout>

    <br.com.mauker.materialsearchview.MaterialSearchView
        android:id="@+id/search_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        style="@style/MaterialSearchViewStyle" />

    <android.support.design.widget.NavigationView ... />

</android.support.v4.widget.DrawerLayout>
```

**Comment by MiralDesai** [comment]
Ok tried that and still not change. Same issue as above. 

I doubt it changes anything but I don't use the NavigationView like in the example above, I use a RecyclverView and build my own custom navigation drawer.

Anyway yeah, the SearchView still shows underneath the status bar.

**Comment by MiralDesai** [comment]
I did a bit of digging and i was able to find the cause of the bug:

In my app theme I have the following for the navigation drawer:

 ```
<item name="android:fitsSystemWindows">true</item>
 <item name="android:windowTranslucentStatus">true</item>
```

If I disable these then the SearchView aligns with the toolbar, however this means that my navigation drawer does not show under the status bar like the material design guidelines show: https://material.google.com/patterns/navigation-drawer.html

So I would say it's a bug with the library not being able to handle this, since the toolbar and other widgets handle it fine.

I'm not quite sure what the fix is but maybe a hack could be to add a status bar margin if those two items are enabled (24dp). I can't do that on my side because it's attached to the toolbar and that moves down too when I try it.

**Comment by MiralDesai** [comment]
With` android:paddingTop="24dp"`:

http://imgur.com/a/VU6vQ

It's a temporary hack, until the library can handle these styles, but yeah it works.

**Comment by Mauker1** [comment]
Just out of curiosity, what happens if you set `android:fitsSystemWindows="true"` to the search view?

**Comment by MiralDesai** [comment]
Hi sorry, been a bit busy and not been working on Search, will have an update today.

**Comment by MiralDesai** [comment]
`android:fitsSystemWindows="true"` doesn't fix the issue. Still have to using `paddingTop`

**Comment by peterbetos** [comment]
Currently checking how Android did it on NavigationView.

**Comment by peterbetos** [comment]
Done, including testing it on CoordinatorLayout. You can check the PR below:

https://github.com/Mauker1/MaterialSearchView/pull/57

**Comment by peterbetos** [comment]
Once the fix is integrated, you can check how I did it on a sample activity using the xml layout below:

(Keep in mind that AppBarLayout's default elevation is 4, so you need to have the SearchBar declared as something higher)

```
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context=".MainActivity"
    android:background="@color/white">

    <android.support.design.widget.AppBarLayout
        android:id="@+id/app_bar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="#607D8B"
            android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
            app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

    </android.support.design.widget.AppBarLayout>

    <android.support.v4.widget.NestedScrollView
        android:layout_width="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"
        android:layout_height="match_parent">

        <RelativeLayout
            android:id="@+id/rl_content"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_below="@+id/toolbar">

            <Button
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerHorizontal="true"
                android:id="@+id/bt_clearHistory"
                android:text="@string/bt_clearHistory" />

            <Button
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_below="@+id/bt_clearHistory"
                android:layout_centerHorizontal="true"
                android:id="@+id/bt_clearSuggestions"
                android:text="@string/bt_clearSuggestions"/>

            <Button
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_below="@+id/bt_clearSuggestions"
                android:layout_centerHorizontal="true"
                android:id="@+id/bt_clearAll"
                android:text="@string/bt_clearAll" />

        </RelativeLayout>
    </android.support.v4.widget.NestedScrollView>

    <br.com.mauker.materialsearchview.MaterialSearchView
        android:id="@+id/search_view"
        android:layout_width="match_parent"
        android:elevation="10dp"
        app:elevation="10dp"
        android:layout_height="match_parent"
        style="@style/MaterialSearchViewStyle"/>

</android.support.design.widget.CoordinatorLayout>
```
