### ISSUE TITLE
Transparent search panel

### ISSUE THREAD

**Issue by FunnyDevs** [Mauker1/MaterialSearchView#4]
Hi! Is possibile to have an option to render transparent searchable panel??? thanks

**Comment by Mauker1** [comment]
Yes, it is! I'll look into that.

**Comment by FunnyDevs** [comment]
Ok, thanks a lot!

**Comment by Mauker1** [comment]
Solved with the last commit. To adjust the transparency, you can either use:

    // From 0.0 to 1.0 (0% to 100%).
    searchView.adjustTintAlpha(float factor);

or

    // From 0 to 255.
    searchView.setTintAlpha(200)

**Comment by hisham2007** [comment]
I used a better approach than using alpha by putting this color inside my app :)

`    <color name="search_layover_bg">@color/black_50</color>`

**Comment by Mauker1** [comment]
Well, that's definitely another good option! 👍
