### ISSUE TITLE
Implement OnItemLongClickListener to history list

### ISSUE THREAD

**Issue by erayasan** [Mauker1/MaterialSearchView#43]
To delete previous searches one by one OnItemLongClickListener could be useful.

**Comment by AdamMc331** [comment]
+1 to that idea. @Mauker1  Can I take this on?

**Comment by erayasan** [comment]
![sample_search_item](https://cloud.githubusercontent.com/assets/14939183/17592834/8d921460-5fec-11e6-9eb4-48a03fdd0ec2.png)

This could be useful also for deleting history searches one by one. Just for an idea :)

**Comment by AdamMc331** [comment]
Oooh. I'll talk to Mauker and see which one he likes better. Having a button in each row item that removes that particular item might be easiest. Although seeing all those "x" symbols might be annoying. I'm torn.

**Comment by erayasan** [comment]
Could be :) I will implement one of the deleting methods but i couldn't decided yet also. Waiting for your precious update. Thanks.

**Comment by AdamMc331** [comment]
Adding a long click listener would be pretty simple, and touches a part of the code I'm decently familiar with which is why I jumped on the ticket haha.

**Comment by AdamMc331** [comment]
Neat! http://imgur.com/jSN5LFn

**Comment by erayasan** [comment]
Thank you for that. This could be useful for now but please consider on other possible deleting options. This search view is getting closer to perfect 💯

**Comment by AdamMc331** [comment]
Absolutely. Something we hope to address is #13 which will give the users (developers using this lib) more control over the search history items and how they work.

**Comment by Mauker1** [comment]
Loved the idea! I'll take a look on the PR soon Adam, thanks! 

And thank you too erayasan!

**Comment by AdamMc331** [comment]
@erayasan 1.1.3 is released!
