### ISSUE TITLE
Implement OnClickListener to voice search icon.

### ISSUE THREAD

**Issue by erayasan** [Mauker1/MaterialSearchView#44]
It is possible to change the drawable of the voice search icon but not the behaviour of it. I opened another issue about deleting history searches. Deleting the history doesn't seems to be user friendly with a button outside the actual search view. I would like to be able to change the icon of the voice search to a trash can and onClick delete all the search history.

OnClickListener for the voice search button could be useful for any purpose.

**Comment by AdamMc331** [comment]
I can add this one in, too.

**Comment by AdamMc331** [comment]
I'm on a roll today. Good thing it's a slow day at the office. http://imgur.com/7oMColQ

**Comment by AdamMc331** [comment]
What I did was give the user the option to add an `OnVoiceClickedListener`, but if you chose not to it would fall back on the default that we have implemented now.

This way, you have the benefit of a default implementation, and we can keep it without screwing over the existing users who take advantage of it.

**Comment by Mauker1** [comment]
I liked the solution, this can be used to change the default behavior of that icon. And it's possible already to change the icon itself too.
