### ISSUE TITLE
ListView is inflating and invisible after first search

### ISSUE THREAD

**Issue by mstedler** [Mauker1/MaterialSearchView#47]
After the first search(with empty history/adapter), if I close and open the activity the ListView is "inflated", as if i call `materialSearchView.openSearch();` but it's invisible, pushing the layout

![ja](https://cloud.githubusercontent.com/assets/13201760/18819203/566ed222-8362-11e6-8945-1d02d9200fd2.png)

Samsung Galaxy s6 
android 6.0.1
lib version 1.1.3

**Comment by Mauker1** [comment]
Could you show your layout XML please?

**Comment by mstedler** [comment]
<android.support.design.widget.AppBarLayout
       android:id="@+id/appbar"
       android:layout_width="match_parent"
       android:layout_height="wrap_content"
       android:theme="@style/AppTheme.AppBarOverlay">

        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:background="?attr/colorPrimary"
                app:popupTheme="@style/AppTheme.PopupOverlay" />

            <br.com.mauker.materialsearchview.MaterialSearchView
                android:id="@+id/search_view"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />
        </FrameLayout>

        <android.support.design.widget.TabLayout
            android:id="@+id/tabs"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

    </android.support.design.widget.AppBarLayout>

**Comment by Mauker1** [comment]
Material Search View is an overlay to all of your layouts, so try to add the following code to the end of your layout:

```xml
<br.com.mauker.materialsearchview.MaterialSearchView
  android:id="@+id/search_view"
  android:layout_width="match_parent"
  android:layout_height="wrap_content" />
```

[Check the sample here.](https://github.com/Mauker1/MaterialSearchView/blob/master/app/src/main/res/layout/activity_main.xml)

**Comment by Mauker1** [comment]
@mstedler did it work?

**Comment by Mauker1** [comment]
Closing the issue as it seems to be a simple layout misplacement.
