### ISSUE TITLE
onQueryTextChange not called

### ISSUE THREAD

**Issue by FunnyDevs** [Mauker1/MaterialSearchView#5]
I have seen that mCurrentQuery && mOldQuery are always equals. I think is better change from CharSequence to String.

**Comment by Mauker1** [comment]
I'll take a look. Thanks!

**Comment by Mauker1** [comment]
I took a look on this part of the code, and it didn't seem to be always true, can you tell me how to reproduce this behavior @FunnyDevs ?

**Comment by FunnyDevs** [comment]
was resolved with 1.1.0 release!

**Comment by Mauker1** [comment]
Oh, OK! Thanks!
