### ISSUE TITLE
Custom searchBarHeight

### ISSUE THREAD

**Issue by peterbetos** [Mauker1/MaterialSearchView#51]
Please check if you can integrate custom searchBarHeight value on your library. You can use the values I did on the following commit:

https://github.com/peterbetos/materialseachview/commit/ce9bb61502e61ba8924cd51e34493d4538b0ad36

Otherwise, let me know if I can fork and pull-request my proposed changes. Thanks.

**Comment by Mauker1** [comment]
I liked the idea. You may do a PR.

**Comment by peterbetos** [comment]
Done :)
