### ISSUE TITLE
Integrate proguard rules inside the library folder

### ISSUE THREAD

**Issue by peterbetos** [Mauker1/MaterialSearchView#52]
Would you be able to apply the following:
http://stackoverflow.com/a/30801516/1931228
This is to prevent apps from forgetting to integrate the proguard rules.

I'll be using your version of the library since it's currently full-featured. (Kudos 👍 ) 
I'll stop updating my fork 😃

**Comment by Mauker1** [comment]
Oh, very nice idea! I'll take a look into that. Thanks!

**Comment by Mauker1** [comment]
@peterbetos Care to take a look [at this](https://travis-ci.org/Mauker1/MaterialSearchView/builds/171247268) and help me figure out what went wrong? I'm not very good with proguard.
I'm postponing this issue to 1.2.1 as I want to release 1.2.0 now.

**Comment by peterbetos** [comment]
Sure @Mauker1  will check this.

**Comment by Mauker1** [comment]
I wasn't expecting to see you so soon haha.
Well, Maybe it can be on 1.2.0 after all 👍

**Comment by Mauker1** [comment]
Solved with the last PR. Thanks @peterbetos 👍 
Btw, I've added your name on the contributors list 😄

**Comment by peterbetos** [comment]
Nice. Thanks @Mauker1 :)
