### ISSUE TITLE
Remove CoordinatorLayout and use an Interface Instead?

### ISSUE THREAD

**Issue by peterbetos** [Mauker1/MaterialSearchView#60]
Is it okay to update the widget to not use `CoordinatorLayout` as its main container? 

This is to encourage developers to layout the whole screen container (on either Activity or Fragment) as a `CoordinatorLayout` instead of placing it inside a widget individually. This is to also facilitate proper arrangement of `AppBarLayout` and other widgets that need to anticipate `Behavior` extensions. 

If you're worrying about having a dedicated `SnackBar` reaction, we can implement it on a listener instead. We can also prepare a custom `Behavior` extension if needed.

**Comment by AdamMc331** [comment]
What are you suggesting be used instead of a `CoordinatorLayout`?

**Comment by peterbetos** [comment]
As simple as RelativeLayout would be enough. If you want something new though, there's ConstraintLayout (so that we can anticipate screen percentage if the need arises).

**Comment by AdamMc331** [comment]
Help me understand - what are the downfalls of using CoordinatorLayout here?

**Comment by peterbetos** [comment]
If you have implementation of a whole screen using CoordinatorLayout for example, then you need to have the MaterialSearchView mimic the behavior of BottomSheet coming up as a new screen (like the one on Google Maps transition from a list to detail), a nested CoordinatorLayout messes up the anticipation of the whole container on what specific scroll `Behavior` to catch (because the nested view will have its own).

**Comment by AdamMc331** [comment]
Hmm. I suppose we can look into making it use a basic RelativeLayout or something. @Mauker1 Do you know if this needs anything coordinatorlayout specific? If not, I can tinker with this tonight.

**Comment by AdamMc331** [comment]
@peterbetos We will be working on this and will have it in for you soon.

**Comment by AdamMc331** [comment]
I went with a FrameLayout since it was the simplest and fastest solution (since it's basically a CoordinatorLayout without behaviors). This way I didn't have to worry about rearranging items in the XML like I would with a LinearLayout or RelativeLayout.

**Comment by peterbetos** [comment]
Thanks @AdamMc331. Will check the jitpack commit.

**Comment by AdamMc331** [comment]
This was merged in but not sure when you can expect an update. I'll reopen this, and I'll close it when it's up.

**Comment by peterbetos** [comment]
Yep. Just for verification purposes 😉

**Comment by AdamMc331** [comment]
@Mauker1  runs the updates. I just help monitor the project and offer a hand when I can haha.

**Comment by Mauker1** [comment]
I'll try to publish the 1.2.0 this week. Then I'll close the issues. Thanks for the support guys.

**Comment by Mauker1** [comment]
@peterbetos @AdamMc331 1.2.0 is out!
