### ISSUE TITLE
searchView suggestion and history list not showing

### ISSUE THREAD

**Issue by arash-jahani** [Mauker1/MaterialSearchView#63]
searchView suggestion and history list not showing when use search bar into custom toolbar

**Comment by peterbetos** [comment]
The search bar is meant to be an overlay from whatever elements are inside the existing layout container. You need to move it outside the Toolbar element.

**Comment by Mauker1** [comment]
Like @peterbetos said, this lib is meant to be an overlay, just place it outside your `Toolbar` and it should be fine.
