### ISSUE TITLE
 Implement a class named MsvAuthority

### ISSUE THREAD

**Issue by rajeevjaiswal** [Mauker1/MaterialSearchView#65]
can any one tell me steps to do the same . Do I need to create a public class which implements MsvAuthority?

**Comment by Mauker1** [comment]
No, that's not what you need to do.

You need to create a class named `MsvAuthority` inside the package `br.com.mauker`.

That class should look something like this:

```java
public class MsvAuthority {
    public static final String CONTENT_AUTHORITY = "com.yourdomain.yourprovider";
}
```

Don't forget to change `com.yourdomain.yourprovider` to your own domain, and you'll also have to use the same value on your `AndroidManifest` file. Like:

```xml
<provider
        android:name="br.com.mauker.materialsearchview.db.HistoryProvider"
        android:authorities="com.yourdomain.yourprovider"
        android:exported="false"
        android:protectionLevel="signature"
        android:syncable="true"/>
```

After that, you're good to go.

You can see an example [here on the sample app code](https://github.com/Mauker1/MaterialSearchView/tree/master/app/src/main).
