### ISSUE TITLE
How can I leave open the search by pressing the enter key?

### ISSUE THREAD

**Issue by volkdown** [Mauker1/MaterialSearchView#70]
Hello! I want to use your library. It looks good. But I have a question. How can I leave open the search by pressing the enter key on the keyboard? The search should only be closed when you press on the back button and the Close button. If I click on the empty field the search should also be open. Thank you in advance

**Comment by peterbetos** [comment]
```
    searchView.setOnQueryTextListener(new MaterialSearchView.OnQueryTextListener() {
            @Override
            public boolean onQueryTextSubmit(String query) {
//Whichever action you want to to             
   return false;
            }
}
```

**Comment by volkdown** [comment]
Hello! Unfortunately I did not get an answer to my question. How can I leave open searchview? I can hold it in the toolbar? When I insert enter key on the keyboard searchview hidden. Is there any way capture searchview, and for example using the method at any time to hide it?

**Comment by Mauker1** [comment]
What peterbetos said should solve your problem.

**Comment by volkdown** [comment]
Thanks got it done, just need to use: return true;
