### ISSUE TITLE
Using SearchView in layout  together with navigation view

### ISSUE THREAD

**Issue by volkdown** [Mauker1/MaterialSearchView#71]
Hello! I have the following problem. When I use your view in the layout with navigation view, then when open the search and I click on item recycler view, search is minimized and lost all of the search results. How should I place your element, so that when you click on the free space on your element search was not closed. I also have another problem. The items in the list suggestions not selected.
My current layout, you can see the following link: http://pastebin.com/3RKEmwY5
Detail problem: http://prntscr.com/dffvu4

**Comment by Mauker1** [comment]
I'll take a look on this.

**Comment by volkdown** [comment]
Okay thanks, I'll wait for your answer. Thank you in advance.

**Comment by Mauker1** [comment]
Let me see if I got this correctly. You want to be able to tap on the "empty" space bellow the search results and keep the search view open?
Are you losing the data, or it's just closing?

**Comment by volkdown** [comment]
Hello! 
1) You want to be able to tap on the "empty" space bellow the search results and keep the search view open? 
-Yes, I want to search view closed only when  user performs an action: clicks the back button, and click on the icon of the cross.
2) Are you losing the data, or it's just closing?
Now the problem is when I click on a list item, the search view is closed. I understand that the search view in an open state occupies the entire layaut. Accordingly, I can not open the item in the list because the action is not passed to the listener item of list. After the search is closed I lose filter list items. Ie search view closes and I lose the filter.

**Comment by Mauker1** [comment]
Ok, so. For the first question, this is the default behavior of the app, and it's defined here:

```Java
    mTintView.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                closeSearch();
            }
        });
```

As for version 1.2.0 it's not possible to change this behavior yet. But I'll add this as a feature so it'll be possible to change this behavior to whatever you want it to do.

As for the second question, you can change the behavior using this method:

`public void setOnItemClickListener(AdapterView.OnItemClickListener listener)`

**Comment by Mauker1** [comment]
You can see an example of that usage on the sample app: https://github.com/Mauker1/MaterialSearchView/blob/master/app/src/main/java/br/com/mauker/materialsearchview/app/MainActivity.java

**Comment by Mauker1** [comment]
I've made possible to disable the default behavior of the tint click, as seem on #84. To do that, you'll just have to call the `setCloseOnTintClick(boolean)` method and set it to `false`.
