### ISSUE TITLE
hide voice button

### ISSUE THREAD

**Issue by hshahdoost** [Mauker1/MaterialSearchView#74]
Is a there a way to totally hide the voice button?

**Comment by Mauker1** [comment]
Yes, as you can see [on this issue](https://github.com/Mauker1/MaterialSearchView/issues/41).

**Comment by hshahdoost** [comment]
It's pretty tricky, Would be a lot better if it was on the docs :-)

**Comment by Mauker1** [comment]
Indeed, the docs need to have more info. I'll open an issue to remind me to update it, thanks!
