### ISSUE TITLE
Main search background

### ISSUE THREAD

**Issue by hshahdoost** [Mauker1/MaterialSearchView#75]
Though search bar, and search item's background's can change, It is impossible to change the gray background of search activity.

**Comment by avalenzuelac** [comment]
Hi! I have the same problem... I appreciate your help, thanks!

**Comment by Mauker1** [comment]
You mean the tint? Where the list shows up after you type something. I believe #37 is related to this.

**Comment by Mauker1** [comment]
It's been 20 days without any response. I'll close this issue. 

Please, take a look at #37, it might be what you're looking for. If it isn't, I'll reopen this issue.
