### ISSUE TITLE
Submitting the query when clicked on suggestion and history

### ISSUE THREAD

**Issue by hshahdoost** [Mauker1/MaterialSearchView#78]
Nothing happens when the user touches a suggestion, While I believe touching a suggestion means the user want to submit it and we should get it as ``onQueryTextSubmit`` event

**Comment by Mauker1** [comment]
You have to define what the suggestion click behavior will be, like the example below:

```java
searchView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                // Do something when the suggestion list is clicked.
                String suggestion = searchView.getSuggestionAtPosition(position);

                searchView.setQuery(suggestion, false);
            }
        });
```

Mind that the `searchView.setQuery(suggestion, false);` method can receive a boolean. If it's `false`, it'll only set the string on the text field, if it's `true` it'll submit the query as soon as you select the suggestion.

**Comment by hshahdoost** [comment]
Thanks, But I think it would be a lot better if there was a default behavior since in almost all of the cases what we want is to submit the query and also the goal of this component is to help us code less

**Comment by Mauker1** [comment]
I liked the idea to make this a default behavior.
