### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by hisham2007** [Mauker1/MaterialSearchView#8]
Thanks for great work.
I will use this lib in Arabic app. the icons doesn't support RTL plus it seems that library is not tested with RTL

**Comment by Mauker1** [comment]
I'll look into it :)

**Comment by hisham2007** [comment]
quick fix for arrow :)
`    View back =  searchView.findViewById(R.id.action_back);
        if (back != null) {
            back.setRotation(180);
        }`

**Comment by Mauker1** [comment]
Can you show me a screenshot of how it looks like right now? Or a mockup :)

**Comment by hisham2007** [comment]
but discovered new issue now on small device with android 4.2 :  
suggestion icon and text are in the middle

**Comment by hisham2007** [comment]
will do it tomorrow as i am trying to deliver now. it is 1:46 AM in Cairo

**Comment by Mauker1** [comment]
Ok, I'll wait for it. Thank you very much for your help!

**Comment by hisham2007** [comment]
I found it:
you are using
android:layout_alignParentLeft="true"

android:layout_toRightOf="@+id/iv_icon"

I know you also used parentStart and toEndOf. But seems that earlier versions (4.2) of Android stick to old values if they found "start" and "left" will select "left"


Final hint for today "as I played with library files :)" : 

In Google play, there is no separator between suggestions so I updated list view to be:

```
 <ListView
            android:id="@+id/suggestion_list"
            android:dividerHeight="0dp"
            android:divider="@null"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
```

and listView item becomes white background with black text

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="?android:attr/listPreferredItemHeight"
    xmlns:tools="http://schemas.android.com/tools"
    android:minHeight="?android:attr/listPreferredItemHeight"
    android:background="@color/white">

    <ImageView
        android:id="@+id/iv_icon" android:tint="@color/black"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"


        android:layout_centerVertical="true"
        android:padding="16dp" />

    <TextView
        android:id="@+id/tv_str"
        tools:text="كايرو"
        android:textColor="@color/black"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_toLeftOf="@+id/iv_icon"
        android:layout_centerVertical="true"
        android:padding="16dp" />
</RelativeLayout>
```

Thanks for great work. You deserve a chocolate, when we meet one day, will give it to you :)

**Comment by Mauker1** [comment]
_"I know you also used parentStart and toEndOf. But seems that earlier versions (4.2) of Android stick to old values if they found "start" and "left" will select "left" "_

As for this part. I believe that the only way to solve it is to create a separated layout file for RTL orientation.

**Comment by Mauker1** [comment]
@hisham2007 Can you share the modifications you already did on this matter? Did you create a separated layout file for the RTL screens? That could help me speed up the next release :)

**Comment by hisham2007** [comment]
Sorry for being late. as my app supports Arabic only for now, here are the modified files:

list_item.xml:

`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="?android:attr/listPreferredItemHeight"
    xmlns:tools="http://schemas.android.com/tools"
    android:minHeight="?android:attr/listPreferredItemHeight"
    android:background="@color/white">

    <ImageView
        android:id="@+id/iv_icon" android:tint="@color/black"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"


        android:layout_centerVertical="true"
        android:padding="16dp" />

    <TextView
        android:id="@+id/tv_str"
        tools:text="كايرو"
        android:textColor="@color/black"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_toLeftOf="@+id/iv_icon"
        android:layout_centerVertical="true"
        android:padding="16dp" />
</RelativeLayout>`

search_view.xml:

`<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/search_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:visibility="gone">

    <View
        android:id="@+id/transparent_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/search_layover_bg" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <LinearLayout
            android:id="@+id/search_bar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="@color/search_field_bg"
            android:orientation="horizontal">

            <ImageButton
                android:id="@+id/action_back"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:background="?android:attr/selectableItemBackground"
                android:contentDescription="@string/cd_up_button"
                android:paddingLeft="@dimen/search_icon_padding"
                android:paddingRight="@dimen/search_icon_padding"
                android:src="@drawable/ic_action_navigation_arrow_back" />

            <EditText
                android:id="@+id/et_search"
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:background="@null"
                android:hint="@string/search_hint"
                android:imeOptions="actionSearch"
                android:paddingLeft="@dimen/search_view_text_padding"
                android:paddingRight="@dimen/search_view_text_padding"
                android:singleLine="true"
                android:textColor="@color/black"
                android:textColorHint="@color/gray_50"
                android:textCursorDrawable="@null"
                />

            <ImageButton
                android:id="@+id/action_voice"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:background="?android:attr/selectableItemBackground"
                android:contentDescription="@string/cd_voice_search"
                android:paddingLeft="@dimen/search_icon_padding"
                android:paddingRight="@dimen/search_icon_padding"
                android:src="@drawable/ic_action_voice_search" />

            <ImageButton
                android:id="@+id/action_clear"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:background="?android:attr/selectableItemBackground"
                android:contentDescription="@string/cd_clear_button"
                android:paddingLeft="@dimen/search_icon_padding"
                android:paddingRight="@dimen/search_icon_padding"
                android:src="@drawable/ic_action_navigation_close"
                android:visibility="gone" />
        </LinearLayout>

        <ListView
            android:id="@+id/suggestion_list"
            android:dividerHeight="0dp"
            android:divider="@null"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
    </LinearLayout>
</android.support.design.widget.CoordinatorLayout>`

**Comment by peterbetos** [comment]
Is this closed already? If not yet, you can apply the following changes:

https://github.com/peterbetos/materialseachview/commit/c9be9f62966793a6f62efe10201d49a66608c4eb

Then use vector icons of course for immediate automirror.

**Comment by Mauker1** [comment]
Not closed yet. Can you make a PR? I'll add the vector icons.

**Comment by Mauker1** [comment]
@peterbetos Not closed yet. Can you make a PR? I'll add the vector icons.

**Comment by peterbetos** [comment]
Done:
https://github.com/Mauker1/MaterialSearchView/pull/53

**Comment by Mauker1** [comment]
Man, you're fast :) Thanks a lot for the help, let's just wait until the CI finishes so I can merge it.

**Comment by peterbetos** [comment]
No prob @Mauker1 👍 
@hisham2007 Once this is released, you can try the editText field as well. It should follow RTL now 😉

**Comment by Mauker1** [comment]
It's working. It will be on the next release.
