### ISSUE TITLE
Capture click on back button into material searchView

### ISSUE THREAD

**Issue by avalenzuelac** [Mauker1/MaterialSearchView#80]
Hi!
Thank you very much for your contribution. My question is:
how capture click on back button into searchView?

I appreciate your help.

Thanks!

**Comment by Mauker1** [comment]
You want to close the view using the back button? Try this:

```java
@Override
public void onBackPressed() {
    if (searchView.isOpen()) {
        // Close the search on the back button press.
        searchView.closeSearch();
    } else {
        super.onBackPressed();
    }
}
```

**Comment by avalenzuelac** [comment]
i found the solution in this post, thank you so much. Regards.

[https://github.com/Mauker1/MaterialSearchView/issues/14](url)

**Comment by Mauker1** [comment]
Yeah, it's exactly that. You're welcome!
