### ISSUE TITLE
when u are release version 1.2.1 ?

### ISSUE THREAD

**Issue by arceleno** [Mauker1/MaterialSearchView#86]
i'm need to use query entered in search box in Material Search View 

and i ask it's like 
searchview.getquery();

**Comment by Mauker1** [comment]
Version 1.2.1 is scheduled to launch on February 28th. But it might come out sooner.

**Comment by arceleno** [comment]
and me can use query entered in Material Search View 
and can use it for ex. search in websites by app

**Comment by Mauker1** [comment]
You can use it, this method will be on the next version.

**Comment by Mauker1** [comment]
@arceleno Version 1.2.2 is out.
