### ISSUE TITLE
problem.. when i use the library  in  layout ??

### ISSUE THREAD

**Issue by arceleno** [Mauker1/MaterialSearchView#87]
Rendering Problems The following classes could not be instantiated:
```java
- br.com.mauker.materialsearchview.MaterialSearchView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE  
Exception Details java.lang.NullPointerException   
at br.com.mauker.materialsearchview.MaterialSearchView.isVoiceAvailable(MaterialSearchView.java:899)   at 
br.com.mauker.materialsearchview.MaterialSearchView.displayVoiceButton(MaterialSearchView.java:434)   at
br.com.mauker.materialsearchview.MaterialSearchView.init(MaterialSearchView.java:260)   at
 br.com.mauker.materialsearchview.MaterialSearchView.<init>(MaterialSearchView.java:205)   at 
br.com.mauker.materialsearchview.MaterialSearchView.<init>(MaterialSearchView.java:193)   at 
java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at 
android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:806)   at 
android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)   at 
android.view.LayoutInflater.rInflate(LayoutInflater.java:782)   at 
android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:809)   at 
android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)   at 
android.view.LayoutInflater.rInflate(LayoutInflater.java:782)   at 
android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:809)   at 
android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)   at 
android.view.LayoutInflater.rInflate(LayoutInflater.java:782)   at 
android.view.LayoutInflater.inflate(LayoutInflater.java:504)   at 
android.view.LayoutInflater.inflate(LayoutInflater.java:385)
```

**Comment by Mauker1** [comment]
Could you please post your XML?

**Comment by arceleno** [comment]
sry for late :))

this my XML

<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    tools:context="com.example.ahmed.recommendersystem.SearchActivity"
    android:id="@+id/search">





    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/AppTheme.AppBarOverlay">


        <android.support.v7.widget.Toolbar
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:id="@+id/toolbar2"
            android:background="@color/black"
            android:elevation="8dp"
            app:popupTheme="@style/AppTheme.PopupOverlay"
            >

        </android.support.v7.widget.Toolbar>



    </android.support.design.widget.AppBarLayout>




    <include layout="@layout/fragment_search_activity"/>


    <br.com.mauker.materialsearchview.MaterialSearchView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/search_view"
        style="@style/MaterialSearchViewStyle"/>



</android.support.design.widget.CoordinatorLayout>

**Comment by hshahdoost** [comment]
I am experiencing the same problem in my project

**Comment by Mauker1** [comment]
Does the library run? Or the problem is only on the preview?

**Comment by arceleno** [comment]
@Mauker1  yes  library run ^^
the problem in preview in android studio
and i wana to ask something
 library work fine in api 17 ? or make problems ?
 cause i'm testing it in api 17 make  problem in suggestion list library ... contents  in xml   show in suggestion  list library  
  .. but in api 21 work fine :( and that's problem not appear

**Comment by Mauker1** [comment]
I will have to dig further into that.
