### ISSUE TITLE
help from your sample u make it to shown your library?

### ISSUE THREAD

**Issue by arceleno** [Mauker1/MaterialSearchView#90]
please, can upload your code for Sample you make and u show it in Doc ?

i'm need to see what library use in actionBar ?

thx

**Comment by peterbetos** [comment]
The sample app is included on the repo:
https://github.com/Mauker1/MaterialSearchView/tree/master/app

**Comment by Mauker1** [comment]
The sample code can be found on that link that @peterbetos provided. If this doesn't answer your question, please comment and I'll reopen this issue.

**Comment by arceleno** [comment]
@Mauker1  that's help thanks but i want to know how to change text color in Suggestion list ??

**Comment by Mauker1** [comment]
It's not possible at the moment. But it'll be on a future release.
