### ISSUE TITLE
keyboard search action not enabled, search EditText can input more than 1 line.

### ISSUE THREAD

**Issue by westlinkin** [Mauker1/MaterialSearchView#91]
![device-2017-03-06-221205](https://cloud.githubusercontent.com/assets/1687198/23613335/fe2ce84c-02b9-11e7-8590-3b6d3738eac5.png)
 
As you can see on the screen shot, the keyboard action button should be a `search icon`, not `next line` icon.

And the voice search is not working, how can I remove the voice icon?

I created the `MaterialSearchView` programmatically in Java code and added into `android.R.id.content` as a child view. 

Nexus 5, with android version 6.0.1

**Comment by AdamMc331** [comment]
We can definitely update the keyboard to use a search icon instead. I will take this ticket.

**Comment by AdamMc331** [comment]
@Mauker1 Do we have a simple way to hide the voice icon or disable it? If not, we should create a separate ticket for that.

**Comment by westlinkin** [comment]
You need to add `android:inputType="text"` attribute of the `et_search` `EdtiText`

**Comment by arceleno** [comment]
u add in style="@style/MaterialSearchViewStyle" ?

like this 

<br.com.mauker.materialsearchview.MaterialSearchView
    android:id="@+id/search_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    style="@style/MaterialSearchViewStyle"/> ???

**Comment by Mauker1** [comment]
Like @westlinkin said, we need the `android:inputType="text"` attribute. And this issue is virtually the same as the #97. We will fix this.
