### ISSUE TITLE
no "search" button in keyboard on HTC

### ISSUE THREAD

**Issue by gregEstoke** [Mauker1/MaterialSearchView#97]
(android:imeOptions="actionSearch|flagNoExtractUi") but my keyboard doesn't display a loupe or a search specific button (only a enter button) Is that specific to the manufacturer or do I need to add something else?
_tested on HTC one M8 Lollipop_

**Comment by Mauker1** [comment]
I'll take a look into this.

**Comment by Mauker1** [comment]
It seems this issue already existed. I'll close this one and we will notify when it's fixed on #91 .
