### ISSUE TITLE
Is there any way to capture the cross (X) click that deletes the input?

### ISSUE THREAD

**Issue by gregEstoke** [Mauker1/MaterialSearchView#98]
I need a specific method for that. Is there any?

**Comment by Mauker1** [comment]
You mean, a callback for the input?

**Comment by gregEstoke** [comment]
no, a callback when the "X" has been clicked.
I guess the only way to do what I want is to check for the parameter of onQueryTextChange to be empty String ...

**Comment by Mauker1** [comment]
Yeah, I believe that currently that's the only way around it now. We could add a callback method for that. 

Could you tell me what are you trying to achieve?

**Comment by Mauker1** [comment]
I could add a callback for that button, it should do the trick.

**Comment by gregEstoke** [comment]
Yes! :) Thank you!
