### ISSUE TITLE
Convert ListView To RecyclerView

### ISSUE THREAD

**Issue by AdamMc331** [Mauker1/MaterialSearchView#99]
Converting to RecyclerView will 1) Be more modern and 2) Allow us to allow the users to have additional control over the MSV.

**Comment by Mauker1** [comment]
As this issue will force us to drop the `CursorAdapter`, and the `ContentProvider` along with it, I'm changing the milestone for 2.0

**Comment by dineshmm23** [comment]
Currently the library handles the adapter itself using a SearchAdapter. Let's give the user the option to override this - which will also give them freedom to display the suggestion items using MSV.
